//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avto.AdoBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tariff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tariff()
        {
            this.User = new HashSet<User>();
        }
    
        public int IdTariff { get; set; }
        public string NameTariff { get; set; }
        public int price { get; set; }
        public int IdSim { get; set; }
        public int IdTv { get; set; }
        public int IdModem { get; set; }
        public int IdInternet { get; set; }
    
        public virtual Internet Internet { get; set; }
        public virtual Modem Modem { get; set; }
        public virtual Sim Sim { get; set; }
        public virtual TV TV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> User { get; set; }
    }
}
