//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avto.AdoBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewUser
    {
        public string NameServices { get; set; }
        public string NameRole { get; set; }
        public int IdUser { get; set; }
        public string LoginUser { get; set; }
        public string PasswordUser { get; set; }
        public int IdRole { get; set; }
        public string Expr1 { get; set; }
        public int IdServices { get; set; }
        public int IdTariff { get; set; }
        public int IdBalance { get; set; }
        public double Money { get; set; }
        public string NameTariff { get; set; }
        public int price { get; set; }
        public int IdSim { get; set; }
        public string nameTv { get; set; }
        public string Number { get; set; }
        public string nameModem { get; set; }
        public double speed { get; set; }
        public int amountModem { get; set; }
        public int priceModem { get; set; }
        public int IdTv { get; set; }
        public int IdModem { get; set; }
        public int IdInternet { get; set; }
    }
}
