//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avto.AdoBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_1
    {
        public string NameServices { get; set; }
        public string NameRole { get; set; }
        public int Expr1 { get; set; }
        public string Expr2 { get; set; }
        public int Expr3 { get; set; }
        public int Expr4 { get; set; }
        public string Expr5 { get; set; }
        public int IdUser { get; set; }
        public string LoginUser { get; set; }
        public string PasswordUser { get; set; }
        public int IdRole { get; set; }
        public int IdServices { get; set; }
    }
}
